In [63]:
import numpy as np

In [64]:
mylist = [1,2,3]

In [65]:
type(mylist)

list

<h4>Converting python list to numpy array object with .array method   
</h4>

In [66]:
myarray = np.array(mylist)

In [67]:
myarray

array([1, 2, 3])

In [68]:
type(myarray)

numpy.ndarray

<h4>"arange" function-Same like 'range' in Python </h4>

In [69]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

<h4>np.zeros(shape=(ROWS,COLUMNS), dtype=float, order='c')<h4>

In [102]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
 np.ones((2,4)) #shape(Hieght of Image, Width of Image)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<h4>np.random.seed() --> Same random number for each time</h4>
<h4>np.random.randint(low,high,number size) --> </h4>

In [73]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [74]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [75]:
arr2 = np.random.randint(0,100,10)

In [76]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

<h4>Max - Min - Location - Mean</h4>

In [77]:
arr.max()

95

In [78]:
arr.min()

9

In [79]:
arr.argmax()

0

In [80]:
arr.argmin()

7

In [81]:
arr.mean()

60.8

In [82]:
arr.reshape((2,5)) # Must be present 2*5 elemets in array 

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

<h4>Concept of Mat</h4>
<h5>Indexing in Mat</h5>
<h5>Slicing in Mat</h5>
<h5>Copy of MAt</h5>

In [83]:
mat = np.arange(0,100).reshape(10,10)

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
row = 0
col = 1

In [86]:
mat[row,col]

1

In [87]:
mat[:,1] # Returns all elements in particular column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [88]:
mat[:,1].reshape(10,1) # For specific shape

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [89]:
mat[2,:] # Returns all elemts in particular raw

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
mat[0:3,0:3] # Slicing from array 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [91]:
mat[0:3,0:4] = 0 # All elements will be 0 in sliced array 

In [92]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
mynewmat = mat.copy() # For copy 

In [94]:
mynewmat[0:6,:] = 7

In [95]:
mynewmat

array([[ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

<h6>=======================================</h6>
<h6>=======================================</h6>
<h1>Numpy Images</h1>
<h6>=======================================</h6>
<h6>=======================================</h6>

-> Images(PNG/JPEG) are represented as an array    (Gray Scale - Black(1)/White(0)) <br>
-> More pixel - better resolution <br>
-> Often default images values between 0-255 (8-    bit number) <br>
-> Divide all the values by 255 (max) to normalize between 0 and 1 --HELPS TO MAKE COMPUTATIONS LESS/EASY <br>
-> Colour images - Red,Green,Blue (R,G,B) produces range of colours <br>
-> The shape of the colour array has 3 dimensions - HIEGHT, WIDTH, COLOUR CHANNEL